version: "3.9"
services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped